server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit-9002 #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.139:3306/tensquare_recruit?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
    generate-ddl: true # 是否自动建表
