server:    # 端口
  port: 9005
spring:
  application:  # 服务名称，为后续的服务注册做准备的
    name: tensquare-gathering-9001
  datasource:  # 数据源
    url: jdbc:mysql://192.168.11.139:3306/tensquare_gathering?characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa: # spring data jpa配置
    show-sql: true # 打印sql语句
    generate-ddl: true # 是否自动建表
    database: mysql  # 数据库类型